// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// UsageLogCreate is the builder for creating a UsageLog entity.
type UsageLogCreate struct {
	config
	mutation *UsageLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UsageLogCreate) SetUserID(v int64) *UsageLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *UsageLogCreate) SetAPIKeyID(v int64) *UsageLogCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *UsageLogCreate) SetAccountID(v int64) *UsageLogCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *UsageLogCreate) SetRequestID(v string) *UsageLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *UsageLogCreate) SetModel(v string) *UsageLogCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetRequestedModel sets the "requested_model" field.
func (_c *UsageLogCreate) SetRequestedModel(v string) *UsageLogCreate {
	_c.mutation.SetRequestedModel(v)
	return _c
}

// SetNillableRequestedModel sets the "requested_model" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableRequestedModel(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetRequestedModel(*v)
	}
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *UsageLogCreate) SetUpstreamModel(v string) *UsageLogCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableUpstreamModel(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetUpstreamModel(*v)
	}
	return _c
}

// SetUpstreamResponseModel sets the "upstream_response_model" field.
func (_c *UsageLogCreate) SetUpstreamResponseModel(v string) *UsageLogCreate {
	_c.mutation.SetUpstreamResponseModel(v)
	return _c
}

// SetNillableUpstreamResponseModel sets the "upstream_response_model" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableUpstreamResponseModel(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetUpstreamResponseModel(*v)
	}
	return _c
}

// SetUpstreamModelMismatch sets the "upstream_model_mismatch" field.
func (_c *UsageLogCreate) SetUpstreamModelMismatch(v bool) *UsageLogCreate {
	_c.mutation.SetUpstreamModelMismatch(v)
	return _c
}

// SetNillableUpstreamModelMismatch sets the "upstream_model_mismatch" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableUpstreamModelMismatch(v *bool) *UsageLogCreate {
	if v != nil {
		_c.SetUpstreamModelMismatch(*v)
	}
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *UsageLogCreate) SetChannelID(v int64) *UsageLogCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableChannelID(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetChannelID(*v)
	}
	return _c
}

// SetModelMappingChain sets the "model_mapping_chain" field.
func (_c *UsageLogCreate) SetModelMappingChain(v string) *UsageLogCreate {
	_c.mutation.SetModelMappingChain(v)
	return _c
}

// SetNillableModelMappingChain sets the "model_mapping_chain" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableModelMappingChain(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetModelMappingChain(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *UsageLogCreate) SetGroupID(v int64) *UsageLogCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableGroupID(v *int64) *UsageLogCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *UsageLogCreate) SetInputTokens(v int) *UsageLogCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableInputTokens(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetInputTokens(*v)
	}
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *UsageLogCreate) SetOutputTokens(v int) *UsageLogCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableOutputTokens(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetOutputTokens(*v)
	}
	return _c
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_c *UsageLogCreate) SetCacheCreationTokens(v int) *UsageLogCreate {
	_c.mutation.SetCacheCreationTokens(v)
	return _c
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCacheCreationTokens(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetCacheCreationTokens(*v)
	}
	return _c
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_c *UsageLogCreate) SetCacheReadTokens(v int) *UsageLogCreate {
	_c.mutation.SetCacheReadTokens(v)
	return _c
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCacheReadTokens(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetCacheReadTokens(*v)
	}
	return _c
}

// SetCacheCreation5mTokens sets the "cache_creation_5m_tokens" field.
func (_c *UsageLogCreate) SetCacheCreation5mTokens(v int) *UsageLogCreate {
	_c.mutation.SetCacheCreation5mTokens(v)
	return _c
}

// SetNillableCacheCreation5mTokens sets the "cache_creation_5m_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCacheCreation5mTokens(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetCacheCreation5mTokens(*v)
	}
	return _c
}

// SetCacheCreation1hTokens sets the "cache_creation_1h_tokens" field.
func (_c *UsageLogCreate) SetCacheCreation1hTokens(v int) *UsageLogCreate {
	_c.mutation.SetCacheCreation1hTokens(v)
	return _c
}

// SetNillableCacheCreation1hTokens sets the "cache_creation_1h_tokens" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCacheCreation1hTokens(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetCacheCreation1hTokens(*v)
	}
	return _c
}

// SetStream sets the "stream" field.
func (_c *UsageLogCreate) SetStream(v bool) *UsageLogCreate {
	_c.mutation.SetStream(v)
	return _c
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableStream(v *bool) *UsageLogCreate {
	if v != nil {
		_c.SetStream(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *UsageLogCreate) SetDurationMs(v int) *UsageLogCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableDurationMs(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (_c *UsageLogCreate) SetFirstTokenMs(v int) *UsageLogCreate {
	_c.mutation.SetFirstTokenMs(v)
	return _c
}

// SetNillableFirstTokenMs sets the "first_token_ms" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableFirstTokenMs(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetFirstTokenMs(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *UsageLogCreate) SetUserAgent(v string) *UsageLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableUserAgent(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *UsageLogCreate) SetIPAddress(v string) *UsageLogCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableIPAddress(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetImageCount sets the "image_count" field.
func (_c *UsageLogCreate) SetImageCount(v int) *UsageLogCreate {
	_c.mutation.SetImageCount(v)
	return _c
}

// SetNillableImageCount sets the "image_count" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableImageCount(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetImageCount(*v)
	}
	return _c
}

// SetImageSize sets the "image_size" field.
func (_c *UsageLogCreate) SetImageSize(v string) *UsageLogCreate {
	_c.mutation.SetImageSize(v)
	return _c
}

// SetNillableImageSize sets the "image_size" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableImageSize(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetImageSize(*v)
	}
	return _c
}

// SetImageInputSize sets the "image_input_size" field.
func (_c *UsageLogCreate) SetImageInputSize(v string) *UsageLogCreate {
	_c.mutation.SetImageInputSize(v)
	return _c
}

// SetNillableImageInputSize sets the "image_input_size" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableImageInputSize(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetImageInputSize(*v)
	}
	return _c
}

// SetImageOutputSize sets the "image_output_size" field.
func (_c *UsageLogCreate) SetImageOutputSize(v string) *UsageLogCreate {
	_c.mutation.SetImageOutputSize(v)
	return _c
}

// SetNillableImageOutputSize sets the "image_output_size" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableImageOutputSize(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetImageOutputSize(*v)
	}
	return _c
}

// SetImageSizeSource sets the "image_size_source" field.
func (_c *UsageLogCreate) SetImageSizeSource(v string) *UsageLogCreate {
	_c.mutation.SetImageSizeSource(v)
	return _c
}

// SetNillableImageSizeSource sets the "image_size_source" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableImageSizeSource(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetImageSizeSource(*v)
	}
	return _c
}

// SetImageSizeBreakdown sets the "image_size_breakdown" field.
func (_c *UsageLogCreate) SetImageSizeBreakdown(v map[string]int) *UsageLogCreate {
	_c.mutation.SetImageSizeBreakdown(v)
	return _c
}

// SetVideoCount sets the "video_count" field.
func (_c *UsageLogCreate) SetVideoCount(v int) *UsageLogCreate {
	_c.mutation.SetVideoCount(v)
	return _c
}

// SetNillableVideoCount sets the "video_count" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableVideoCount(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetVideoCount(*v)
	}
	return _c
}

// SetVideoResolution sets the "video_resolution" field.
func (_c *UsageLogCreate) SetVideoResolution(v string) *UsageLogCreate {
	_c.mutation.SetVideoResolution(v)
	return _c
}

// SetNillableVideoResolution sets the "video_resolution" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableVideoResolution(v *string) *UsageLogCreate {
	if v != nil {
		_c.SetVideoResolution(*v)
	}
	return _c
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (_c *UsageLogCreate) SetVideoDurationSeconds(v int) *UsageLogCreate {
	_c.mutation.SetVideoDurationSeconds(v)
	return _c
}

// SetNillableVideoDurationSeconds sets the "video_duration_seconds" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableVideoDurationSeconds(v *int) *UsageLogCreate {
	if v != nil {
		_c.SetVideoDurationSeconds(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageLogCreate) SetCreatedAt(v time.Time) *UsageLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageLogCreate) SetNillableCreatedAt(v *time.Time) *UsageLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UsageLogCreate) SetUser(v *User) *UsageLogCreate {
	return _c.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *UsageLogCreate) SetAPIKey(v *APIKey) *UsageLogCreate {
	return _c.SetAPIKeyID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *UsageLogCreate) SetAccount(v *Account) *UsageLogCreate {
	return _c.SetAccountID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *UsageLogCreate) SetGroup(v *Group) *UsageLogCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the UsageLogMutation object of the builder.
func (_c *UsageLogCreate) Mutation() *UsageLogMutation {
	return _c.mutation
}

// Save creates the UsageLog in the database.
func (_c *UsageLogCreate) Save(ctx context.Context) (*UsageLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageLogCreate) SaveX(ctx context.Context) *UsageLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageLogCreate) defaults() {
	if _, ok := _c.mutation.InputTokens(); !ok {
		v := usagelog.DefaultInputTokens
		_c.mutation.SetInputTokens(v)
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		v := usagelog.DefaultOutputTokens
		_c.mutation.SetOutputTokens(v)
	}
	if _, ok := _c.mutation.CacheCreationTokens(); !ok {
		v := usagelog.DefaultCacheCreationTokens
		_c.mutation.SetCacheCreationTokens(v)
	}
	if _, ok := _c.mutation.CacheReadTokens(); !ok {
		v := usagelog.DefaultCacheReadTokens
		_c.mutation.SetCacheReadTokens(v)
	}
	if _, ok := _c.mutation.CacheCreation5mTokens(); !ok {
		v := usagelog.DefaultCacheCreation5mTokens
		_c.mutation.SetCacheCreation5mTokens(v)
	}
	if _, ok := _c.mutation.CacheCreation1hTokens(); !ok {
		v := usagelog.DefaultCacheCreation1hTokens
		_c.mutation.SetCacheCreation1hTokens(v)
	}
	if _, ok := _c.mutation.Stream(); !ok {
		v := usagelog.DefaultStream
		_c.mutation.SetStream(v)
	}
	if _, ok := _c.mutation.ImageCount(); !ok {
		v := usagelog.DefaultImageCount
		_c.mutation.SetImageCount(v)
	}
	if _, ok := _c.mutation.VideoCount(); !ok {
		v := usagelog.DefaultVideoCount
		_c.mutation.SetVideoCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usagelog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageLogCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UsageLog.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "UsageLog.api_key_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "UsageLog.account_id"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "UsageLog.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := usagelog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "UsageLog.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "UsageLog.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := usagelog.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "UsageLog.model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RequestedModel(); ok {
		if err := usagelog.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "UsageLog.requested_model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := usagelog.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "UsageLog.upstream_model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamResponseModel(); ok {
		if err := usagelog.UpstreamResponseModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_response_model", err: fmt.Errorf(`ent: validator failed for field "UsageLog.upstream_response_model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ModelMappingChain(); ok {
		if err := usagelog.ModelMappingChainValidator(v); err != nil {
			return &ValidationError{Name: "model_mapping_chain", err: fmt.Errorf(`ent: validator failed for field "UsageLog.model_mapping_chain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		return &ValidationError{Name: "input_tokens", err: errors.New(`ent: missing required field "UsageLog.input_tokens"`)}
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		return &ValidationError{Name: "output_tokens", err: errors.New(`ent: missing required field "UsageLog.output_tokens"`)}
	}
	if _, ok := _c.mutation.CacheCreationTokens(); !ok {
		return &ValidationError{Name: "cache_creation_tokens", err: errors.New(`ent: missing required field "UsageLog.cache_creation_tokens"`)}
	}
	if _, ok := _c.mutation.CacheReadTokens(); !ok {
		return &ValidationError{Name: "cache_read_tokens", err: errors.New(`ent: missing required field "UsageLog.cache_read_tokens"`)}
	}
	if _, ok := _c.mutation.CacheCreation5mTokens(); !ok {
		return &ValidationError{Name: "cache_creation_5m_tokens", err: errors.New(`ent: missing required field "UsageLog.cache_creation_5m_tokens"`)}
	}
	if _, ok := _c.mutation.CacheCreation1hTokens(); !ok {
		return &ValidationError{Name: "cache_creation_1h_tokens", err: errors.New(`ent: missing required field "UsageLog.cache_creation_1h_tokens"`)}
	}
	if _, ok := _c.mutation.Stream(); !ok {
		return &ValidationError{Name: "stream", err: errors.New(`ent: missing required field "UsageLog.stream"`)}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := usagelog.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "UsageLog.user_agent": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := usagelog.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "UsageLog.ip_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ImageCount(); !ok {
		return &ValidationError{Name: "image_count", err: errors.New(`ent: missing required field "UsageLog.image_count"`)}
	}
	if v, ok := _c.mutation.ImageSize(); ok {
		if err := usagelog.ImageSizeValidator(v); err != nil {
			return &ValidationError{Name: "image_size", err: fmt.Errorf(`ent: validator failed for field "UsageLog.image_size": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ImageInputSize(); ok {
		if err := usagelog.ImageInputSizeValidator(v); err != nil {
			return &ValidationError{Name: "image_input_size", err: fmt.Errorf(`ent: validator failed for field "UsageLog.image_input_size": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ImageOutputSize(); ok {
		if err := usagelog.ImageOutputSizeValidator(v); err != nil {
			return &ValidationError{Name: "image_output_size", err: fmt.Errorf(`ent: validator failed for field "UsageLog.image_output_size": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ImageSizeSource(); ok {
		if err := usagelog.ImageSizeSourceValidator(v); err != nil {
			return &ValidationError{Name: "image_size_source", err: fmt.Errorf(`ent: validator failed for field "UsageLog.image_size_source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VideoCount(); !ok {
		return &ValidationError{Name: "video_count", err: errors.New(`ent: missing required field "UsageLog.video_count"`)}
	}
	if v, ok := _c.mutation.VideoResolution(); ok {
		if err := usagelog.VideoResolutionValidator(v); err != nil {
			return &ValidationError{Name: "video_resolution", err: fmt.Errorf(`ent: validator failed for field "UsageLog.video_resolution": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageLog.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UsageLog.user"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "UsageLog.api_key"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "UsageLog.account"`)}
	}
	return nil
}

func (_c *UsageLogCreate) sqlSave(ctx context.Context) (*UsageLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageLogCreate) createSpec() (*UsageLog, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagelog.Table, sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(usagelog.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(usagelog.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.RequestedModel(); ok {
		_spec.SetField(usagelog.FieldRequestedModel, field.TypeString, value)
		_node.RequestedModel = &value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(usagelog.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = &value
	}
	if value, ok := _c.mutation.UpstreamResponseModel(); ok {
		_spec.SetField(usagelog.FieldUpstreamResponseModel, field.TypeString, value)
		_node.UpstreamResponseModel = &value
	}
	if value, ok := _c.mutation.UpstreamModelMismatch(); ok {
		_spec.SetField(usagelog.FieldUpstreamModelMismatch, field.TypeBool, value)
		_node.UpstreamModelMismatch = &value
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(usagelog.FieldChannelID, field.TypeInt64, value)
		_node.ChannelID = &value
	}
	if value, ok := _c.mutation.ModelMappingChain(); ok {
		_spec.SetField(usagelog.FieldModelMappingChain, field.TypeString, value)
		_node.ModelMappingChain = &value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(usagelog.FieldInputTokens, field.TypeInt, value)
		_node.InputTokens = value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(usagelog.FieldOutputTokens, field.TypeInt, value)
		_node.OutputTokens = value
	}
	if value, ok := _c.mutation.CacheCreationTokens(); ok {
		_spec.SetField(usagelog.FieldCacheCreationTokens, field.TypeInt, value)
		_node.CacheCreationTokens = value
	}
	if value, ok := _c.mutation.CacheReadTokens(); ok {
		_spec.SetField(usagelog.FieldCacheReadTokens, field.TypeInt, value)
		_node.CacheReadTokens = value
	}
	if value, ok := _c.mutation.CacheCreation5mTokens(); ok {
		_spec.SetField(usagelog.FieldCacheCreation5mTokens, field.TypeInt, value)
		_node.CacheCreation5mTokens = value
	}
	if value, ok := _c.mutation.CacheCreation1hTokens(); ok {
		_spec.SetField(usagelog.FieldCacheCreation1hTokens, field.TypeInt, value)
		_node.CacheCreation1hTokens = value
	}
	if value, ok := _c.mutation.Stream(); ok {
		_spec.SetField(usagelog.FieldStream, field.TypeBool, value)
		_node.Stream = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(usagelog.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = &value
	}
	if value, ok := _c.mutation.FirstTokenMs(); ok {
		_spec.SetField(usagelog.FieldFirstTokenMs, field.TypeInt, value)
		_node.FirstTokenMs = &value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(usagelog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = &value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(usagelog.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = &value
	}
	if value, ok := _c.mutation.ImageCount(); ok {
		_spec.SetField(usagelog.FieldImageCount, field.TypeInt, value)
		_node.ImageCount = value
	}
	if value, ok := _c.mutation.ImageSize(); ok {
		_spec.SetField(usagelog.FieldImageSize, field.TypeString, value)
		_node.ImageSize = &value
	}
	if value, ok := _c.mutation.ImageInputSize(); ok {
		_spec.SetField(usagelog.FieldImageInputSize, field.TypeString, value)
		_node.ImageInputSize = &value
	}
	if value, ok := _c.mutation.ImageOutputSize(); ok {
		_spec.SetField(usagelog.FieldImageOutputSize, field.TypeString, value)
		_node.ImageOutputSize = &value
	}
	if value, ok := _c.mutation.ImageSizeSource(); ok {
		_spec.SetField(usagelog.FieldImageSizeSource, field.TypeString, value)
		_node.ImageSizeSource = &value
	}
	if value, ok := _c.mutation.ImageSizeBreakdown(); ok {
		_spec.SetField(usagelog.FieldImageSizeBreakdown, field.TypeJSON, value)
		_node.ImageSizeBreakdown = value
	}
	if value, ok := _c.mutation.VideoCount(); ok {
		_spec.SetField(usagelog.FieldVideoCount, field.TypeInt, value)
		_node.VideoCount = value
	}
	if value, ok := _c.mutation.VideoResolution(); ok {
		_spec.SetField(usagelog.FieldVideoResolution, field.TypeString, value)
		_node.VideoResolution = &value
	}
	if value, ok := _c.mutation.VideoDurationSeconds(); ok {
		_spec.SetField(usagelog.FieldVideoDurationSeconds, field.TypeInt, value)
		_node.VideoDurationSeconds = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagelog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.UserTable,
			Columns: []string{usagelog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.APIKeyTable,
			Columns: []string{usagelog.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.AccountTable,
			Columns: []string{usagelog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usagelog.GroupTable,
			Columns: []string{usagelog.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageLog.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageLogUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageLogCreate) OnConflict(opts ...sql.ConflictOption) *UsageLogUpsertOne {
	_c.conflict = opts
	return &UsageLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageLogCreate) OnConflictColumns(columns ...string) *UsageLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageLogUpsertOne{
		create: _c,
	}
}

type (
	// UsageLogUpsertOne is the builder for "upsert"-ing
	//  one UsageLog node.
	UsageLogUpsertOne struct {
		create *UsageLogCreate
	}

	// UsageLogUpsert is the "OnConflict" setter.
	UsageLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UsageLogUpsert) SetUserID(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateUserID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UsageLogUpsert) SetAPIKeyID(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateAPIKeyID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldAPIKeyID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *UsageLogUpsert) SetAccountID(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateAccountID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldAccountID)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *UsageLogUpsert) SetRequestID(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateRequestID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldRequestID)
	return u
}

// SetModel sets the "model" field.
func (u *UsageLogUpsert) SetModel(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateModel() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldModel)
	return u
}

// SetRequestedModel sets the "requested_model" field.
func (u *UsageLogUpsert) SetRequestedModel(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldRequestedModel, v)
	return u
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateRequestedModel() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldRequestedModel)
	return u
}

// ClearRequestedModel clears the value of the "requested_model" field.
func (u *UsageLogUpsert) ClearRequestedModel() *UsageLogUpsert {
	u.SetNull(usagelog.FieldRequestedModel)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *UsageLogUpsert) SetUpstreamModel(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateUpstreamModel() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldUpstreamModel)
	return u
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (u *UsageLogUpsert) ClearUpstreamModel() *UsageLogUpsert {
	u.SetNull(usagelog.FieldUpstreamModel)
	return u
}

// SetUpstreamResponseModel sets the "upstream_response_model" field.
func (u *UsageLogUpsert) SetUpstreamResponseModel(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldUpstreamResponseModel, v)
	return u
}

// UpdateUpstreamResponseModel sets the "upstream_response_model" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateUpstreamResponseModel() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldUpstreamResponseModel)
	return u
}

// ClearUpstreamResponseModel clears the value of the "upstream_response_model" field.
func (u *UsageLogUpsert) ClearUpstreamResponseModel() *UsageLogUpsert {
	u.SetNull(usagelog.FieldUpstreamResponseModel)
	return u
}

// SetUpstreamModelMismatch sets the "upstream_model_mismatch" field.
func (u *UsageLogUpsert) SetUpstreamModelMismatch(v bool) *UsageLogUpsert {
	u.Set(usagelog.FieldUpstreamModelMismatch, v)
	return u
}

// UpdateUpstreamModelMismatch sets the "upstream_model_mismatch" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateUpstreamModelMismatch() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldUpstreamModelMismatch)
	return u
}

// ClearUpstreamModelMismatch clears the value of the "upstream_model_mismatch" field.
func (u *UsageLogUpsert) ClearUpstreamModelMismatch() *UsageLogUpsert {
	u.SetNull(usagelog.FieldUpstreamModelMismatch)
	return u
}

// SetChannelID sets the "channel_id" field.
func (u *UsageLogUpsert) SetChannelID(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldChannelID, v)
	return u
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateChannelID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldChannelID)
	return u
}

// AddChannelID adds v to the "channel_id" field.
func (u *UsageLogUpsert) AddChannelID(v int64) *UsageLogUpsert {
	u.Add(usagelog.FieldChannelID, v)
	return u
}

// ClearChannelID clears the value of the "channel_id" field.
func (u *UsageLogUpsert) ClearChannelID() *UsageLogUpsert {
	u.SetNull(usagelog.FieldChannelID)
	return u
}

// SetModelMappingChain sets the "model_mapping_chain" field.
func (u *UsageLogUpsert) SetModelMappingChain(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldModelMappingChain, v)
	return u
}

// UpdateModelMappingChain sets the "model_mapping_chain" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateModelMappingChain() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldModelMappingChain)
	return u
}

// ClearModelMappingChain clears the value of the "model_mapping_chain" field.
func (u *UsageLogUpsert) ClearModelMappingChain() *UsageLogUpsert {
	u.SetNull(usagelog.FieldModelMappingChain)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *UsageLogUpsert) SetGroupID(v int64) *UsageLogUpsert {
	u.Set(usagelog.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateGroupID() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldGroupID)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *UsageLogUpsert) ClearGroupID() *UsageLogUpsert {
	u.SetNull(usagelog.FieldGroupID)
	return u
}

// SetInputTokens sets the "input_tokens" field.
func (u *UsageLogUpsert) SetInputTokens(v int) *UsageLogUpsert {
	u.Set(usagelog.FieldInputTokens, v)
	return u
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateInputTokens() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldInputTokens)
	return u
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *UsageLogUpsert) AddInputTokens(v int) *UsageLogUpsert {
	u.Add(usagelog.FieldInputTokens, v)
	return u
}

// SetOutputTokens sets the "output_tokens" field.
func (u *UsageLogUpsert) SetOutputTokens(v int) *UsageLogUpsert {
	u.Set(usagelog.FieldOutputTokens, v)
	return u
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateOutputTokens() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldOutputTokens)
	return u
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *UsageLogUpsert) AddOutputTokens(v int) *UsageLogUpsert {
	u.Add(usagelog.FieldOutputTokens, v)
	return u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (u *UsageLogUpsert) SetCacheCreationTokens(v int) *UsageLogUpsert {
	u.Set(usagelog.FieldCacheCreationTokens, v)
	return u
}

// UpdateCacheCreationTokens sets the "cache_creation_tokens" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateCacheCreationTokens() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldCacheCreationTokens)
	return u
}

// AddCacheCreationTokens adds v to the "cache_creation_tokens" field.
func (u *UsageLogUpsert) AddCacheCreationTokens(v int) *UsageLogUpsert {
	u.Add(usagelog.FieldCacheCreationTokens, v)
	return u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (u *UsageLogUpsert) SetCacheReadTokens(v int) *UsageLogUpsert {
	u.Set(usagelog.FieldCacheReadTokens, v)
	return u
}

// UpdateCacheReadTokens sets the "cache_read_tokens" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateCacheReadTokens() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldCacheReadTokens)
	return u
}

// AddCacheReadTokens adds v to the "cache_read_tokens" field.
func (u *UsageLogUpsert) AddCacheReadTokens(v int) *UsageLogUpsert {
	u.Add(usagelog.FieldCacheReadTokens, v)
	return u
}

// SetCacheCreation5mTokens sets the "cache_creation_5m_tokens" field.
func (u *UsageLogUpsert) SetCacheCreation5mTokens(v int) *UsageLogUpsert {
	u.Set(usagelog.FieldCacheCreation5mTokens, v)
	return u
}

// UpdateCacheCreation5mTokens sets the "cache_creation_5m_tokens" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateCacheCreation5mTokens() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldCacheCreation5mTokens)
	return u
}

// AddCacheCreation5mTokens adds v to the "cache_creation_5m_tokens" field.
func (u *UsageLogUpsert) AddCacheCreation5mTokens(v int) *UsageLogUpsert {
	u.Add(usagelog.FieldCacheCreation5mTokens, v)
	return u
}

// SetCacheCreation1hTokens sets the "cache_creation_1h_tokens" field.
func (u *UsageLogUpsert) SetCacheCreation1hTokens(v int) *UsageLogUpsert {
	u.Set(usagelog.FieldCacheCreation1hTokens, v)
	return u
}

// UpdateCacheCreation1hTokens sets the "cache_creation_1h_tokens" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateCacheCreation1hTokens() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldCacheCreation1hTokens)
	return u
}

// AddCacheCreation1hTokens adds v to the "cache_creation_1h_tokens" field.
func (u *UsageLogUpsert) AddCacheCreation1hTokens(v int) *UsageLogUpsert {
	u.Add(usagelog.FieldCacheCreation1hTokens, v)
	return u
}

// SetStream sets the "stream" field.
func (u *UsageLogUpsert) SetStream(v bool) *UsageLogUpsert {
	u.Set(usagelog.FieldStream, v)
	return u
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateStream() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldStream)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *UsageLogUpsert) SetDurationMs(v int) *UsageLogUpsert {
	u.Set(usagelog.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateDurationMs() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *UsageLogUpsert) AddDurationMs(v int) *UsageLogUpsert {
	u.Add(usagelog.FieldDurationMs, v)
	return u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *UsageLogUpsert) ClearDurationMs() *UsageLogUpsert {
	u.SetNull(usagelog.FieldDurationMs)
	return u
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (u *UsageLogUpsert) SetFirstTokenMs(v int) *UsageLogUpsert {
	u.Set(usagelog.FieldFirstTokenMs, v)
	return u
}

// UpdateFirstTokenMs sets the "first_token_ms" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateFirstTokenMs() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldFirstTokenMs)
	return u
}

// AddFirstTokenMs adds v to the "first_token_ms" field.
func (u *UsageLogUpsert) AddFirstTokenMs(v int) *UsageLogUpsert {
	u.Add(usagelog.FieldFirstTokenMs, v)
	return u
}

// ClearFirstTokenMs clears the value of the "first_token_ms" field.
func (u *UsageLogUpsert) ClearFirstTokenMs() *UsageLogUpsert {
	u.SetNull(usagelog.FieldFirstTokenMs)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *UsageLogUpsert) SetUserAgent(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateUserAgent() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldUserAgent)
	return u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *UsageLogUpsert) ClearUserAgent() *UsageLogUpsert {
	u.SetNull(usagelog.FieldUserAgent)
	return u
}

// SetIPAddress sets the "ip_address" field.
func (u *UsageLogUpsert) SetIPAddress(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldIPAddress, v)
	return u
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateIPAddress() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldIPAddress)
	return u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *UsageLogUpsert) ClearIPAddress() *UsageLogUpsert {
	u.SetNull(usagelog.FieldIPAddress)
	return u
}

// SetImageCount sets the "image_count" field.
func (u *UsageLogUpsert) SetImageCount(v int) *UsageLogUpsert {
	u.Set(usagelog.FieldImageCount, v)
	return u
}

// UpdateImageCount sets the "image_count" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateImageCount() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldImageCount)
	return u
}

// AddImageCount adds v to the "image_count" field.
func (u *UsageLogUpsert) AddImageCount(v int) *UsageLogUpsert {
	u.Add(usagelog.FieldImageCount, v)
	return u
}

// SetImageSize sets the "image_size" field.
func (u *UsageLogUpsert) SetImageSize(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldImageSize, v)
	return u
}

// UpdateImageSize sets the "image_size" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateImageSize() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldImageSize)
	return u
}

// ClearImageSize clears the value of the "image_size" field.
func (u *UsageLogUpsert) ClearImageSize() *UsageLogUpsert {
	u.SetNull(usagelog.FieldImageSize)
	return u
}

// SetImageInputSize sets the "image_input_size" field.
func (u *UsageLogUpsert) SetImageInputSize(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldImageInputSize, v)
	return u
}

// UpdateImageInputSize sets the "image_input_size" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateImageInputSize() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldImageInputSize)
	return u
}

// ClearImageInputSize clears the value of the "image_input_size" field.
func (u *UsageLogUpsert) ClearImageInputSize() *UsageLogUpsert {
	u.SetNull(usagelog.FieldImageInputSize)
	return u
}

// SetImageOutputSize sets the "image_output_size" field.
func (u *UsageLogUpsert) SetImageOutputSize(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldImageOutputSize, v)
	return u
}

// UpdateImageOutputSize sets the "image_output_size" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateImageOutputSize() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldImageOutputSize)
	return u
}

// ClearImageOutputSize clears the value of the "image_output_size" field.
func (u *UsageLogUpsert) ClearImageOutputSize() *UsageLogUpsert {
	u.SetNull(usagelog.FieldImageOutputSize)
	return u
}

// SetImageSizeSource sets the "image_size_source" field.
func (u *UsageLogUpsert) SetImageSizeSource(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldImageSizeSource, v)
	return u
}

// UpdateImageSizeSource sets the "image_size_source" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateImageSizeSource() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldImageSizeSource)
	return u
}

// ClearImageSizeSource clears the value of the "image_size_source" field.
func (u *UsageLogUpsert) ClearImageSizeSource() *UsageLogUpsert {
	u.SetNull(usagelog.FieldImageSizeSource)
	return u
}

// SetImageSizeBreakdown sets the "image_size_breakdown" field.
func (u *UsageLogUpsert) SetImageSizeBreakdown(v map[string]int) *UsageLogUpsert {
	u.Set(usagelog.FieldImageSizeBreakdown, v)
	return u
}

// UpdateImageSizeBreakdown sets the "image_size_breakdown" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateImageSizeBreakdown() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldImageSizeBreakdown)
	return u
}

// ClearImageSizeBreakdown clears the value of the "image_size_breakdown" field.
func (u *UsageLogUpsert) ClearImageSizeBreakdown() *UsageLogUpsert {
	u.SetNull(usagelog.FieldImageSizeBreakdown)
	return u
}

// SetVideoCount sets the "video_count" field.
func (u *UsageLogUpsert) SetVideoCount(v int) *UsageLogUpsert {
	u.Set(usagelog.FieldVideoCount, v)
	return u
}

// UpdateVideoCount sets the "video_count" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateVideoCount() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldVideoCount)
	return u
}

// AddVideoCount adds v to the "video_count" field.
func (u *UsageLogUpsert) AddVideoCount(v int) *UsageLogUpsert {
	u.Add(usagelog.FieldVideoCount, v)
	return u
}

// SetVideoResolution sets the "video_resolution" field.
func (u *UsageLogUpsert) SetVideoResolution(v string) *UsageLogUpsert {
	u.Set(usagelog.FieldVideoResolution, v)
	return u
}

// UpdateVideoResolution sets the "video_resolution" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateVideoResolution() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldVideoResolution)
	return u
}

// ClearVideoResolution clears the value of the "video_resolution" field.
func (u *UsageLogUpsert) ClearVideoResolution() *UsageLogUpsert {
	u.SetNull(usagelog.FieldVideoResolution)
	return u
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (u *UsageLogUpsert) SetVideoDurationSeconds(v int) *UsageLogUpsert {
	u.Set(usagelog.FieldVideoDurationSeconds, v)
	return u
}

// UpdateVideoDurationSeconds sets the "video_duration_seconds" field to the value that was provided on create.
func (u *UsageLogUpsert) UpdateVideoDurationSeconds() *UsageLogUpsert {
	u.SetExcluded(usagelog.FieldVideoDurationSeconds)
	return u
}

// AddVideoDurationSeconds adds v to the "video_duration_seconds" field.
func (u *UsageLogUpsert) AddVideoDurationSeconds(v int) *UsageLogUpsert {
	u.Add(usagelog.FieldVideoDurationSeconds, v)
	return u
}

// ClearVideoDurationSeconds clears the value of the "video_duration_seconds" field.
func (u *UsageLogUpsert) ClearVideoDurationSeconds() *UsageLogUpsert {
	u.SetNull(usagelog.FieldVideoDurationSeconds)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageLogUpsertOne) UpdateNewValues() *UsageLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usagelog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UsageLogUpsertOne) Ignore() *UsageLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageLogUpsertOne) DoNothing() *UsageLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageLogCreate.OnConflict
// documentation for more info.
func (u *UsageLogUpsertOne) Update(set func(*UsageLogUpsert)) *UsageLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UsageLogUpsertOne) SetUserID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateUserID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UsageLogUpsertOne) SetAPIKeyID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateAPIKeyID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UsageLogUpsertOne) SetAccountID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateAccountID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateAccountID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *UsageLogUpsertOne) SetRequestID(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateRequestID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateRequestID()
	})
}

// SetModel sets the "model" field.
func (u *UsageLogUpsertOne) SetModel(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateModel() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateModel()
	})
}

// SetRequestedModel sets the "requested_model" field.
func (u *UsageLogUpsertOne) SetRequestedModel(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetRequestedModel(v)
	})
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateRequestedModel() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateRequestedModel()
	})
}

// ClearRequestedModel clears the value of the "requested_model" field.
func (u *UsageLogUpsertOne) ClearRequestedModel() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearRequestedModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *UsageLogUpsertOne) SetUpstreamModel(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateUpstreamModel() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateUpstreamModel()
	})
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (u *UsageLogUpsertOne) ClearUpstreamModel() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearUpstreamModel()
	})
}

// SetUpstreamResponseModel sets the "upstream_response_model" field.
func (u *UsageLogUpsertOne) SetUpstreamResponseModel(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetUpstreamResponseModel(v)
	})
}

// UpdateUpstreamResponseModel sets the "upstream_response_model" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateUpstreamResponseModel() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateUpstreamResponseModel()
	})
}

// ClearUpstreamResponseModel clears the value of the "upstream_response_model" field.
func (u *UsageLogUpsertOne) ClearUpstreamResponseModel() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearUpstreamResponseModel()
	})
}

// SetUpstreamModelMismatch sets the "upstream_model_mismatch" field.
func (u *UsageLogUpsertOne) SetUpstreamModelMismatch(v bool) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetUpstreamModelMismatch(v)
	})
}

// UpdateUpstreamModelMismatch sets the "upstream_model_mismatch" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateUpstreamModelMismatch() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateUpstreamModelMismatch()
	})
}

// ClearUpstreamModelMismatch clears the value of the "upstream_model_mismatch" field.
func (u *UsageLogUpsertOne) ClearUpstreamModelMismatch() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearUpstreamModelMismatch()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *UsageLogUpsertOne) SetChannelID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetChannelID(v)
	})
}

// AddChannelID adds v to the "channel_id" field.
func (u *UsageLogUpsertOne) AddChannelID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateChannelID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateChannelID()
	})
}

// ClearChannelID clears the value of the "channel_id" field.
func (u *UsageLogUpsertOne) ClearChannelID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearChannelID()
	})
}

// SetModelMappingChain sets the "model_mapping_chain" field.
func (u *UsageLogUpsertOne) SetModelMappingChain(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetModelMappingChain(v)
	})
}

// UpdateModelMappingChain sets the "model_mapping_chain" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateModelMappingChain() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateModelMappingChain()
	})
}

// ClearModelMappingChain clears the value of the "model_mapping_chain" field.
func (u *UsageLogUpsertOne) ClearModelMappingChain() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearModelMappingChain()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UsageLogUpsertOne) SetGroupID(v int64) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateGroupID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *UsageLogUpsertOne) ClearGroupID() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearGroupID()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *UsageLogUpsertOne) SetInputTokens(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *UsageLogUpsertOne) AddInputTokens(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateInputTokens() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *UsageLogUpsertOne) SetOutputTokens(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *UsageLogUpsertOne) AddOutputTokens(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateOutputTokens() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (u *UsageLogUpsertOne) SetCacheCreationTokens(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCacheCreationTokens(v)
	})
}

// AddCacheCreationTokens adds v to the "cache_creation_tokens" field.
func (u *UsageLogUpsertOne) AddCacheCreationTokens(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCacheCreationTokens(v)
	})
}

// UpdateCacheCreationTokens sets the "cache_creation_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateCacheCreationTokens() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCacheCreationTokens()
	})
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (u *UsageLogUpsertOne) SetCacheReadTokens(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCacheReadTokens(v)
	})
}

// AddCacheReadTokens adds v to the "cache_read_tokens" field.
func (u *UsageLogUpsertOne) AddCacheReadTokens(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCacheReadTokens(v)
	})
}

// UpdateCacheReadTokens sets the "cache_read_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateCacheReadTokens() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCacheReadTokens()
	})
}

// SetCacheCreation5mTokens sets the "cache_creation_5m_tokens" field.
func (u *UsageLogUpsertOne) SetCacheCreation5mTokens(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCacheCreation5mTokens(v)
	})
}

// AddCacheCreation5mTokens adds v to the "cache_creation_5m_tokens" field.
func (u *UsageLogUpsertOne) AddCacheCreation5mTokens(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCacheCreation5mTokens(v)
	})
}

// UpdateCacheCreation5mTokens sets the "cache_creation_5m_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateCacheCreation5mTokens() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCacheCreation5mTokens()
	})
}

// SetCacheCreation1hTokens sets the "cache_creation_1h_tokens" field.
func (u *UsageLogUpsertOne) SetCacheCreation1hTokens(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCacheCreation1hTokens(v)
	})
}

// AddCacheCreation1hTokens adds v to the "cache_creation_1h_tokens" field.
func (u *UsageLogUpsertOne) AddCacheCreation1hTokens(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCacheCreation1hTokens(v)
	})
}

// UpdateCacheCreation1hTokens sets the "cache_creation_1h_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateCacheCreation1hTokens() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCacheCreation1hTokens()
	})
}

// SetStream sets the "stream" field.
func (u *UsageLogUpsertOne) SetStream(v bool) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateStream() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateStream()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *UsageLogUpsertOne) SetDurationMs(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *UsageLogUpsertOne) AddDurationMs(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateDurationMs() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *UsageLogUpsertOne) ClearDurationMs() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearDurationMs()
	})
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (u *UsageLogUpsertOne) SetFirstTokenMs(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetFirstTokenMs(v)
	})
}

// AddFirstTokenMs adds v to the "first_token_ms" field.
func (u *UsageLogUpsertOne) AddFirstTokenMs(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddFirstTokenMs(v)
	})
}

// UpdateFirstTokenMs sets the "first_token_ms" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateFirstTokenMs() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateFirstTokenMs()
	})
}

// ClearFirstTokenMs clears the value of the "first_token_ms" field.
func (u *UsageLogUpsertOne) ClearFirstTokenMs() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearFirstTokenMs()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *UsageLogUpsertOne) SetUserAgent(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateUserAgent() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *UsageLogUpsertOne) ClearUserAgent() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *UsageLogUpsertOne) SetIPAddress(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateIPAddress() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateIPAddress()
	})
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *UsageLogUpsertOne) ClearIPAddress() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearIPAddress()
	})
}

// SetImageCount sets the "image_count" field.
func (u *UsageLogUpsertOne) SetImageCount(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetImageCount(v)
	})
}

// AddImageCount adds v to the "image_count" field.
func (u *UsageLogUpsertOne) AddImageCount(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddImageCount(v)
	})
}

// UpdateImageCount sets the "image_count" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateImageCount() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateImageCount()
	})
}

// SetImageSize sets the "image_size" field.
func (u *UsageLogUpsertOne) SetImageSize(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetImageSize(v)
	})
}

// UpdateImageSize sets the "image_size" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateImageSize() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateImageSize()
	})
}

// ClearImageSize clears the value of the "image_size" field.
func (u *UsageLogUpsertOne) ClearImageSize() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearImageSize()
	})
}

// SetImageInputSize sets the "image_input_size" field.
func (u *UsageLogUpsertOne) SetImageInputSize(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetImageInputSize(v)
	})
}

// UpdateImageInputSize sets the "image_input_size" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateImageInputSize() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateImageInputSize()
	})
}

// ClearImageInputSize clears the value of the "image_input_size" field.
func (u *UsageLogUpsertOne) ClearImageInputSize() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearImageInputSize()
	})
}

// SetImageOutputSize sets the "image_output_size" field.
func (u *UsageLogUpsertOne) SetImageOutputSize(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetImageOutputSize(v)
	})
}

// UpdateImageOutputSize sets the "image_output_size" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateImageOutputSize() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateImageOutputSize()
	})
}

// ClearImageOutputSize clears the value of the "image_output_size" field.
func (u *UsageLogUpsertOne) ClearImageOutputSize() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearImageOutputSize()
	})
}

// SetImageSizeSource sets the "image_size_source" field.
func (u *UsageLogUpsertOne) SetImageSizeSource(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetImageSizeSource(v)
	})
}

// UpdateImageSizeSource sets the "image_size_source" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateImageSizeSource() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateImageSizeSource()
	})
}

// ClearImageSizeSource clears the value of the "image_size_source" field.
func (u *UsageLogUpsertOne) ClearImageSizeSource() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearImageSizeSource()
	})
}

// SetImageSizeBreakdown sets the "image_size_breakdown" field.
func (u *UsageLogUpsertOne) SetImageSizeBreakdown(v map[string]int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetImageSizeBreakdown(v)
	})
}

// UpdateImageSizeBreakdown sets the "image_size_breakdown" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateImageSizeBreakdown() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateImageSizeBreakdown()
	})
}

// ClearImageSizeBreakdown clears the value of the "image_size_breakdown" field.
func (u *UsageLogUpsertOne) ClearImageSizeBreakdown() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearImageSizeBreakdown()
	})
}

// SetVideoCount sets the "video_count" field.
func (u *UsageLogUpsertOne) SetVideoCount(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetVideoCount(v)
	})
}

// AddVideoCount adds v to the "video_count" field.
func (u *UsageLogUpsertOne) AddVideoCount(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddVideoCount(v)
	})
}

// UpdateVideoCount sets the "video_count" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateVideoCount() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateVideoCount()
	})
}

// SetVideoResolution sets the "video_resolution" field.
func (u *UsageLogUpsertOne) SetVideoResolution(v string) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetVideoResolution(v)
	})
}

// UpdateVideoResolution sets the "video_resolution" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateVideoResolution() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateVideoResolution()
	})
}

// ClearVideoResolution clears the value of the "video_resolution" field.
func (u *UsageLogUpsertOne) ClearVideoResolution() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearVideoResolution()
	})
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (u *UsageLogUpsertOne) SetVideoDurationSeconds(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetVideoDurationSeconds(v)
	})
}

// AddVideoDurationSeconds adds v to the "video_duration_seconds" field.
func (u *UsageLogUpsertOne) AddVideoDurationSeconds(v int) *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddVideoDurationSeconds(v)
	})
}

// UpdateVideoDurationSeconds sets the "video_duration_seconds" field to the value that was provided on create.
func (u *UsageLogUpsertOne) UpdateVideoDurationSeconds() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateVideoDurationSeconds()
	})
}

// ClearVideoDurationSeconds clears the value of the "video_duration_seconds" field.
func (u *UsageLogUpsertOne) ClearVideoDurationSeconds() *UsageLogUpsertOne {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearVideoDurationSeconds()
	})
}

// Exec executes the query.
func (u *UsageLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UsageLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UsageLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UsageLogCreateBulk is the builder for creating many UsageLog entities in bulk.
type UsageLogCreateBulk struct {
	config
	err      error
	builders []*UsageLogCreate
	conflict []sql.ConflictOption
}

// Save creates the UsageLog entities in the database.
func (_c *UsageLogCreateBulk) Save(ctx context.Context) ([]*UsageLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageLogCreateBulk) SaveX(ctx context.Context) []*UsageLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageLogUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *UsageLogUpsertBulk {
	_c.conflict = opts
	return &UsageLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageLogCreateBulk) OnConflictColumns(columns ...string) *UsageLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageLogUpsertBulk{
		create: _c,
	}
}

// UsageLogUpsertBulk is the builder for "upsert"-ing
// a bulk of UsageLog nodes.
type UsageLogUpsertBulk struct {
	create *UsageLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageLogUpsertBulk) UpdateNewValues() *UsageLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usagelog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UsageLogUpsertBulk) Ignore() *UsageLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageLogUpsertBulk) DoNothing() *UsageLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageLogCreateBulk.OnConflict
// documentation for more info.
func (u *UsageLogUpsertBulk) Update(set func(*UsageLogUpsert)) *UsageLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UsageLogUpsertBulk) SetUserID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateUserID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *UsageLogUpsertBulk) SetAPIKeyID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateAPIKeyID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *UsageLogUpsertBulk) SetAccountID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateAccountID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateAccountID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *UsageLogUpsertBulk) SetRequestID(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateRequestID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateRequestID()
	})
}

// SetModel sets the "model" field.
func (u *UsageLogUpsertBulk) SetModel(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateModel() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateModel()
	})
}

// SetRequestedModel sets the "requested_model" field.
func (u *UsageLogUpsertBulk) SetRequestedModel(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetRequestedModel(v)
	})
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateRequestedModel() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateRequestedModel()
	})
}

// ClearRequestedModel clears the value of the "requested_model" field.
func (u *UsageLogUpsertBulk) ClearRequestedModel() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearRequestedModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *UsageLogUpsertBulk) SetUpstreamModel(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateUpstreamModel() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateUpstreamModel()
	})
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (u *UsageLogUpsertBulk) ClearUpstreamModel() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearUpstreamModel()
	})
}

// SetUpstreamResponseModel sets the "upstream_response_model" field.
func (u *UsageLogUpsertBulk) SetUpstreamResponseModel(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetUpstreamResponseModel(v)
	})
}

// UpdateUpstreamResponseModel sets the "upstream_response_model" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateUpstreamResponseModel() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateUpstreamResponseModel()
	})
}

// ClearUpstreamResponseModel clears the value of the "upstream_response_model" field.
func (u *UsageLogUpsertBulk) ClearUpstreamResponseModel() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearUpstreamResponseModel()
	})
}

// SetUpstreamModelMismatch sets the "upstream_model_mismatch" field.
func (u *UsageLogUpsertBulk) SetUpstreamModelMismatch(v bool) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetUpstreamModelMismatch(v)
	})
}

// UpdateUpstreamModelMismatch sets the "upstream_model_mismatch" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateUpstreamModelMismatch() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateUpstreamModelMismatch()
	})
}

// ClearUpstreamModelMismatch clears the value of the "upstream_model_mismatch" field.
func (u *UsageLogUpsertBulk) ClearUpstreamModelMismatch() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearUpstreamModelMismatch()
	})
}

// SetChannelID sets the "channel_id" field.
func (u *UsageLogUpsertBulk) SetChannelID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetChannelID(v)
	})
}

// AddChannelID adds v to the "channel_id" field.
func (u *UsageLogUpsertBulk) AddChannelID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddChannelID(v)
	})
}

// UpdateChannelID sets the "channel_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateChannelID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateChannelID()
	})
}

// ClearChannelID clears the value of the "channel_id" field.
func (u *UsageLogUpsertBulk) ClearChannelID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearChannelID()
	})
}

// SetModelMappingChain sets the "model_mapping_chain" field.
func (u *UsageLogUpsertBulk) SetModelMappingChain(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetModelMappingChain(v)
	})
}

// UpdateModelMappingChain sets the "model_mapping_chain" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateModelMappingChain() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateModelMappingChain()
	})
}

// ClearModelMappingChain clears the value of the "model_mapping_chain" field.
func (u *UsageLogUpsertBulk) ClearModelMappingChain() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearModelMappingChain()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UsageLogUpsertBulk) SetGroupID(v int64) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateGroupID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *UsageLogUpsertBulk) ClearGroupID() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearGroupID()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *UsageLogUpsertBulk) SetInputTokens(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *UsageLogUpsertBulk) AddInputTokens(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateInputTokens() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *UsageLogUpsertBulk) SetOutputTokens(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *UsageLogUpsertBulk) AddOutputTokens(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateOutputTokens() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (u *UsageLogUpsertBulk) SetCacheCreationTokens(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCacheCreationTokens(v)
	})
}

// AddCacheCreationTokens adds v to the "cache_creation_tokens" field.
func (u *UsageLogUpsertBulk) AddCacheCreationTokens(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCacheCreationTokens(v)
	})
}

// UpdateCacheCreationTokens sets the "cache_creation_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateCacheCreationTokens() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCacheCreationTokens()
	})
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (u *UsageLogUpsertBulk) SetCacheReadTokens(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCacheReadTokens(v)
	})
}

// AddCacheReadTokens adds v to the "cache_read_tokens" field.
func (u *UsageLogUpsertBulk) AddCacheReadTokens(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCacheReadTokens(v)
	})
}

// UpdateCacheReadTokens sets the "cache_read_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateCacheReadTokens() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCacheReadTokens()
	})
}

// SetCacheCreation5mTokens sets the "cache_creation_5m_tokens" field.
func (u *UsageLogUpsertBulk) SetCacheCreation5mTokens(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCacheCreation5mTokens(v)
	})
}

// AddCacheCreation5mTokens adds v to the "cache_creation_5m_tokens" field.
func (u *UsageLogUpsertBulk) AddCacheCreation5mTokens(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCacheCreation5mTokens(v)
	})
}

// UpdateCacheCreation5mTokens sets the "cache_creation_5m_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateCacheCreation5mTokens() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCacheCreation5mTokens()
	})
}

// SetCacheCreation1hTokens sets the "cache_creation_1h_tokens" field.
func (u *UsageLogUpsertBulk) SetCacheCreation1hTokens(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetCacheCreation1hTokens(v)
	})
}

// AddCacheCreation1hTokens adds v to the "cache_creation_1h_tokens" field.
func (u *UsageLogUpsertBulk) AddCacheCreation1hTokens(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddCacheCreation1hTokens(v)
	})
}

// UpdateCacheCreation1hTokens sets the "cache_creation_1h_tokens" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateCacheCreation1hTokens() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateCacheCreation1hTokens()
	})
}

// SetStream sets the "stream" field.
func (u *UsageLogUpsertBulk) SetStream(v bool) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateStream() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateStream()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *UsageLogUpsertBulk) SetDurationMs(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *UsageLogUpsertBulk) AddDurationMs(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateDurationMs() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *UsageLogUpsertBulk) ClearDurationMs() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearDurationMs()
	})
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (u *UsageLogUpsertBulk) SetFirstTokenMs(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetFirstTokenMs(v)
	})
}

// AddFirstTokenMs adds v to the "first_token_ms" field.
func (u *UsageLogUpsertBulk) AddFirstTokenMs(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddFirstTokenMs(v)
	})
}

// UpdateFirstTokenMs sets the "first_token_ms" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateFirstTokenMs() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateFirstTokenMs()
	})
}

// ClearFirstTokenMs clears the value of the "first_token_ms" field.
func (u *UsageLogUpsertBulk) ClearFirstTokenMs() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearFirstTokenMs()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *UsageLogUpsertBulk) SetUserAgent(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateUserAgent() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *UsageLogUpsertBulk) ClearUserAgent() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearUserAgent()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *UsageLogUpsertBulk) SetIPAddress(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateIPAddress() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateIPAddress()
	})
}

// ClearIPAddress clears the value of the "ip_address" field.
func (u *UsageLogUpsertBulk) ClearIPAddress() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearIPAddress()
	})
}

// SetImageCount sets the "image_count" field.
func (u *UsageLogUpsertBulk) SetImageCount(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetImageCount(v)
	})
}

// AddImageCount adds v to the "image_count" field.
func (u *UsageLogUpsertBulk) AddImageCount(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddImageCount(v)
	})
}

// UpdateImageCount sets the "image_count" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateImageCount() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateImageCount()
	})
}

// SetImageSize sets the "image_size" field.
func (u *UsageLogUpsertBulk) SetImageSize(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetImageSize(v)
	})
}

// UpdateImageSize sets the "image_size" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateImageSize() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateImageSize()
	})
}

// ClearImageSize clears the value of the "image_size" field.
func (u *UsageLogUpsertBulk) ClearImageSize() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearImageSize()
	})
}

// SetImageInputSize sets the "image_input_size" field.
func (u *UsageLogUpsertBulk) SetImageInputSize(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetImageInputSize(v)
	})
}

// UpdateImageInputSize sets the "image_input_size" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateImageInputSize() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateImageInputSize()
	})
}

// ClearImageInputSize clears the value of the "image_input_size" field.
func (u *UsageLogUpsertBulk) ClearImageInputSize() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearImageInputSize()
	})
}

// SetImageOutputSize sets the "image_output_size" field.
func (u *UsageLogUpsertBulk) SetImageOutputSize(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetImageOutputSize(v)
	})
}

// UpdateImageOutputSize sets the "image_output_size" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateImageOutputSize() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateImageOutputSize()
	})
}

// ClearImageOutputSize clears the value of the "image_output_size" field.
func (u *UsageLogUpsertBulk) ClearImageOutputSize() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearImageOutputSize()
	})
}

// SetImageSizeSource sets the "image_size_source" field.
func (u *UsageLogUpsertBulk) SetImageSizeSource(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetImageSizeSource(v)
	})
}

// UpdateImageSizeSource sets the "image_size_source" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateImageSizeSource() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateImageSizeSource()
	})
}

// ClearImageSizeSource clears the value of the "image_size_source" field.
func (u *UsageLogUpsertBulk) ClearImageSizeSource() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearImageSizeSource()
	})
}

// SetImageSizeBreakdown sets the "image_size_breakdown" field.
func (u *UsageLogUpsertBulk) SetImageSizeBreakdown(v map[string]int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetImageSizeBreakdown(v)
	})
}

// UpdateImageSizeBreakdown sets the "image_size_breakdown" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateImageSizeBreakdown() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateImageSizeBreakdown()
	})
}

// ClearImageSizeBreakdown clears the value of the "image_size_breakdown" field.
func (u *UsageLogUpsertBulk) ClearImageSizeBreakdown() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearImageSizeBreakdown()
	})
}

// SetVideoCount sets the "video_count" field.
func (u *UsageLogUpsertBulk) SetVideoCount(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetVideoCount(v)
	})
}

// AddVideoCount adds v to the "video_count" field.
func (u *UsageLogUpsertBulk) AddVideoCount(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddVideoCount(v)
	})
}

// UpdateVideoCount sets the "video_count" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateVideoCount() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateVideoCount()
	})
}

// SetVideoResolution sets the "video_resolution" field.
func (u *UsageLogUpsertBulk) SetVideoResolution(v string) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetVideoResolution(v)
	})
}

// UpdateVideoResolution sets the "video_resolution" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateVideoResolution() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateVideoResolution()
	})
}

// ClearVideoResolution clears the value of the "video_resolution" field.
func (u *UsageLogUpsertBulk) ClearVideoResolution() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearVideoResolution()
	})
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (u *UsageLogUpsertBulk) SetVideoDurationSeconds(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.SetVideoDurationSeconds(v)
	})
}

// AddVideoDurationSeconds adds v to the "video_duration_seconds" field.
func (u *UsageLogUpsertBulk) AddVideoDurationSeconds(v int) *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.AddVideoDurationSeconds(v)
	})
}

// UpdateVideoDurationSeconds sets the "video_duration_seconds" field to the value that was provided on create.
func (u *UsageLogUpsertBulk) UpdateVideoDurationSeconds() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.UpdateVideoDurationSeconds()
	})
}

// ClearVideoDurationSeconds clears the value of the "video_duration_seconds" field.
func (u *UsageLogUpsertBulk) ClearVideoDurationSeconds() *UsageLogUpsertBulk {
	return u.Update(func(s *UsageLogUpsert) {
		s.ClearVideoDurationSeconds()
	})
}

// Exec executes the query.
func (u *UsageLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UsageLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
